# Generated by Django 4.2.6 on 2023-11-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='posted_by',
            new_name='by',
        ),
    ]
